# Generated by Django 4.2.1 on 2023-05-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_center_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='picture',
            field=models.ImageField(default='static/center/dp/default.png', upload_to='static/center/dp/'),
        ),
    ]
