# Generated by Django 4.2.1 on 2023-05-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_center_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='isAvailble',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='center',
            name='rent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
