# Generated by Django 4.2.1 on 2023-05-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_isavailble_center_isavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='fbLink',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='fullAdd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='igLink',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
