# Generated by Django 4.2.1 on 2023-05-08 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_center_capacity_center_fblink_center_fulladd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateTimeField(blank=True, null=True)),
                ('bookingTime', models.DateTimeField(auto_now_add=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('eventType', models.CharField(blank=True, max_length=500, null=True)),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.center')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
