# Generated by Django 4.2.1 on 2023-05-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trxid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
