# Generated by Django 4.2.1 on 2023-05-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_booking_trxid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
