# Generated by Django 4.2.1 on 2023-05-08 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookingTime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='eventDate',
        ),
    ]
