# Generated by Django 4.2.1 on 2023-05-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='center',
        ),
        migrations.AddField(
            model_name='booking',
            name='center',
            field=models.ManyToManyField(to='home.center'),
        ),
    ]
