# Generated by Django 4.2.1 on 2023-05-08 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_booking_center_booking_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='center',
        ),
        migrations.AddField(
            model_name='booking',
            name='center',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.center'),
        ),
    ]
